# Generated by Django 4.0.2 on 2022-02-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('idade', models.IntegerField(default=0)),
                ('telefone', models.IntegerField(default=0)),
                ('documento', models.IntegerField(default=0)),
            ],
        ),
    ]
